apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-app-deployment
spec:
  selector:
    matchLabels:
      app: task-app
  replicas: 1
  template:
    metadata:
      labels:
        app: task-app
    spec:
      containers:
      - name: task-app
        image: task-app-image:v2
        ports:
        - containerPort: 5000
